# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

env: 
  REACT_APP_SPACE: ${{secrets.REACT_APP_SPACE}}
  REACT_APP_ACCESSTOKEN: ${{secrets.REACT_APP_ACCESSTOKEN}}

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "REACT_APP_ACCESSTOKEN = ${{secrets.REACT_APP_ACCESSTOKEN}}"
      - run: echo "REACT_APP_SPACE = ${{secrets.REACT_APP_SPACE}}"
      - run: npm install
      - run: npm run int-test
